### ISSUE TITLE
very nice tool ! but I find Some can be improved.

### ISSUE THREAD

**Issue by wxa1048989080** [MrFrankel/ruler#6] opened 2017-06-30 09:30 UTC
very nice tool ! Thank you MrFrankel ! This is what I need, but I find Some can be improved.

1. If I call setScale(), the guide line is not follow the Ruler's scale.
2. The same input( setGuides ) can't get the same output ( getGuides ).

**Comment by MrFrankel** [comment] 2017-07-02 06:51
@wxa1048989080 Hey, Thanks for the feedback.

Seems to be bugs introduced recently, Ill look into them.
Also the documentation needs a brush up.

**Comment by MrFrankel** [comment] 2017-07-03 08:44
@wxa1048989080 Ive fixed the issues mentioned and also the demo page.

If you can please verify and can close this issue. thanks.

**Comment by wxa1048989080** [comment] 2017-07-04 12:59
@MrFrankel  Excellent! 
I install the ruler package of version 1.0, after testing,the first problem has bend fixed, but the second question still exists.

I think this section code should changed:
Source line 104
``` 
var constructGuide = function(dimension, x, y, e, isSet) {
        var guideIndex;
        //.....

        if (dimension === VERTICAL) {
            guide.style.left = ruler.prototype.utils.pixelize(x - options.container.getBoundingClientRect().left);

            if (isSet) guide.style.left = ruler.prototype.utils.pixelize( Math.round( x / CUR_SCALE ) + options.rulerHeight );

        } else {
            guide.style.top = ruler.prototype.utils.pixelize(y - options.container.getBoundingClientRect().top);

            if (isSet) guide.style.top = ruler.prototype.utils.pixelize( Math.round( y / CUR_SCALE ) + options.rulerHeight );
        }
       //......
    };
```

**Comment by MrFrankel** [comment] 2017-07-04 13:58
@wxa1048989080 Not quit sure what you mean.
If I do:
`var guides = myRuler.getGuides();`
`myRuler.clearGuides();`
`myRuler.setGuides(guides);`

The guides are applied to the ruler.

Maybe if you can supply a gist reproducing the issue.

**Comment by wxa1048989080** [comment] 2017-07-05 08:17
![Uploading vs.gif…]()

**Comment by wxa1048989080** [comment] 2017-07-05 08:46
![Image of Yaktocat](https://img.alicdn.com/tfs/TB1h2WxSXXXXXbJXFXXXXXXXXXX-1076-725.gif)

**Comment by wxa1048989080** [comment] 2017-07-05 08:50
Got it?

**Comment by MrFrankel** [comment] 2017-07-05 08:53
@wxa1048989080 Yea! got it!
Best bug report ever!

You want to put in a pull request for the fix?

**Comment by MrFrankel** [comment] 2017-07-05 09:43
fixe in #7

**Closed by MrFrankel** 2017-07-05 09:43 UTC
